// src/components/sftp/FileExplorer.tsx
import type { KeyboardEvent, MouseEvent } from 'react';
import type { RemoteEntry, SftpSessionState } from '@/types/sftp';

interface Props {
  state: SftpSessionState;
  onNavigate: (path: string) => void;
  onSelect: (path: string) => void;
  onUpload: () => void;
  onDownload: (paths: string[]) => void;
}

/** 将路径拆分为可点击的面包屑。 */
function pathSegments(path: string) {
  const parts = path.split('/').filter(Boolean);
  return parts.map((label, index) => ({ label, path: `/${parts.slice(0, index + 1).join('/')}` }));
}

/** 格式化远程文件大小。 */
function formatSize(bytes: number) {
  if (bytes === 0) return '—';
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

/** 格式化远程文件修改时间。 */
function formatDate(timestamp: number) {
  return timestamp ? new Date(timestamp).toLocaleDateString('zh-CN') : '';
}

/** 渲染远程路径与文件列表。 */
export default function FileExplorer({ state, onNavigate, onSelect, onUpload, onDownload }: Props) {
  const entries = [...state.entries].sort((a, b) => Number(b.isDir) - Number(a.isDir));

  /** 单击文件时切换选择。 */
  function handleClick(entry: RemoteEntry) {
    if (!entry.isDir) onSelect(entry.path);
  }

  /** 双击目录进入，双击文件下载。 */
  function handleOpen(entry: RemoteEntry) {
    entry.isDir ? onNavigate(entry.path) : onDownload([entry.path]);
  }

  /** 支持键盘 Enter 打开条目。 */
  function handleKey(event: KeyboardEvent, entry: RemoteEntry) {
    if (event.key === 'Enter') handleOpen(entry);
  }

  /** 避免双击文件前的第二次单击改变父级行为。 */
  function handleDoubleClick(event: MouseEvent, entry: RemoteEntry) {
    event.preventDefault();
    handleOpen(entry);
  }

  return (
    <div className="file-explorer">
      <div className="path-bar">
        <button className="path-seg path-seg--root" onClick={() => onNavigate('/')}>/</button>
        {pathSegments(state.currentPath).map((segment) => (
          <span key={segment.path}><span className="path-sep">›</span>
            <button className="path-seg" onClick={() => onNavigate(segment.path)}>{segment.label}</button></span>
        ))}
        <span className="path-actions">
          <button onClick={onUpload}>上传</button>
          <button disabled={state.selectedPaths.size === 0} onClick={() => onDownload([...state.selectedPaths])}>下载</button>
        </span>
      </div>
      {state.loading ? <div className="state-msg">加载中...</div>
        : state.error ? <div className="state-msg state-msg--error">{state.error}</div>
          : entries.length === 0 ? <div className="state-msg">空目录</div>
            : <div className="file-list" role="rowgroup">{entries.map((entry) => (
              <div key={entry.path} data-testid="file-row" className={`file-row ${state.selectedPaths.has(entry.path) ? 'file-row--selected' : ''}`}
                role="row" tabIndex={0} onClick={() => handleClick(entry)} onDoubleClick={(event) => handleDoubleClick(event, entry)}
                onKeyDown={(event) => handleKey(event, entry)}>
                <span className="file-icon">{entry.isDir ? '📁' : '📄'}</span>
                <span className={`file-name ${entry.isDir ? 'file-name--dir' : ''}`}>{entry.name}</span>
                <span className="file-size">{formatSize(entry.size)}</span>
                <span className="file-date">{formatDate(entry.modifiedAt)}</span>
              </div>
            ))}</div>}
    </div>
  );
}

// src/components/sftp/FileExplorer.vue
<script setup lang="ts">
import type { SftpSessionState, RemoteEntry } from '@/types/sftp';

const props = defineProps<{
  state: SftpSessionState;
}>();

const emit = defineEmits<{
  navigate: [path: string];
  select: [path: string];
  upload: [];
  download: [paths: string[]];
}>();

/** 将路径字符串拆分为面包屑片段数组 */
function pathSegments(path: string): { label: string; path: string }[] {
  const parts = path.split('/').filter(Boolean);
  return parts.map((label, i) => ({
    label,
    path: '/' + parts.slice(0, i + 1).join('/'),
  }));
}

/** 格式化文件大小为可读字符串 */
function formatSize(bytes: number): string {
  if (bytes === 0) return '—';
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

/** 格式化毫秒时间戳为日期字符串 */
function formatDate(ms: number): string {
  if (!ms) return '';
  return new Date(ms).toLocaleDateString('zh-CN');
}

/** 处理行点击：文件触发 select，目录不触发 */
function handleRowClick(entry: RemoteEntry) {
  if (!entry.is_dir) {
    emit('select', entry.path);
  }
}

/** 处理行双击：目录触发 navigate，文件触发 download */
function handleRowDblClick(entry: RemoteEntry) {
  if (entry.is_dir) {
    emit('navigate', entry.path);
  } else {
    emit('download', [entry.path]);
  }
}
</script>

<template>
  <div class="file-explorer">
    <!-- 路径导航栏 -->
    <div class="path-bar">
      <span
        class="path-seg path-seg--root"
        role="button"
        tabindex="0"
        @click="emit('navigate', '/')"
        @keydown.enter="emit('navigate', '/')"
      >/</span>
      <template v-for="seg in pathSegments(state.currentPath)" :key="seg.path">
        <span class="path-sep">›</span>
        <span
          class="path-seg"
          role="button"
          tabindex="0"
          @click="emit('navigate', seg.path)"
          @keydown.enter="emit('navigate', seg.path)"
        >{{ seg.label }}</span>
      </template>
    </div>

    <!-- 加载中 -->
    <div v-if="state.loading" class="state-msg">加载中...</div>

    <!-- 错误 -->
    <div v-else-if="state.error" class="state-msg state-msg--error">{{ state.error }}</div>

    <!-- 空目录 -->
    <div v-else-if="state.entries.length === 0" class="state-msg">空目录</div>

    <!-- 文件列表 -->
    <div v-else class="file-list">
      <div
        v-for="entry in state.entries"
        :key="entry.path"
        data-testid="file-row"
        class="file-row"
        :class="{ 'file-row--selected': state.selectedPaths.has(entry.path) }"
        role="row"
        tabindex="0"
        @click="handleRowClick(entry)"
        @dblclick="handleRowDblClick(entry)"
        @keydown.enter="handleRowDblClick(entry)"
      >
        <span class="file-icon">{{ entry.is_dir ? '📁' : '📄' }}</span>
        <span class="file-name" :class="{ 'file-name--dir': entry.is_dir }">{{ entry.name }}</span>
        <span class="file-size">{{ formatSize(entry.size) }}</span>
        <span class="file-date">{{ formatDate(entry.modified_at) }}</span>
      </div>
    </div>
  </div>
</template>

<style scoped>
.file-explorer { display: flex; flex-direction: column; height: 100%; min-height: 0; }
.path-bar {
  display: flex; align-items: center; gap: 4px;
  padding: 0 10px; height: 28px; flex-shrink: 0;
  background: var(--color-panel-bg); border-bottom: 1px solid var(--color-border);
  font-size: 11px;
}
.path-seg { color: #aaa; cursor: pointer; }
.path-seg:hover { color: #e0e0e0; }
.path-sep { color: #444; }
.state-msg { padding: 16px; color: #666; font-size: 12px; text-align: center; }
.state-msg--error { color: #bf6a6a; }
.file-list { flex: 1; overflow-y: auto; padding: 4px 0; }
.file-row {
  display: flex; align-items: center; gap: 8px;
  padding: 4px 12px; cursor: pointer; border-radius: 2px; margin: 0 4px;
  font-size: 11px;
}
.file-row:hover { background: var(--color-hover, #252525); }
.file-row--selected { background: var(--color-selected, #1a3a5a); }
.file-icon { width: 14px; flex-shrink: 0; }
.file-name { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: #ccc; }
.file-name--dir { color: #7ab8f5; }
.file-size { color: #555; width: 60px; text-align: right; flex-shrink: 0; }
.file-date { color: #444; width: 80px; text-align: right; flex-shrink: 0; }
</style>
