// src/components/host/HostEditorDialog.tsx
import { useEffect, useState } from 'react';
import { Form, Input, InputNumber, Modal, Select } from 'antd';
import { AuthType, type HostConfig, type SaveHostRequest } from '@/types/host';

interface Props {
  open: boolean;
  editingHost: HostConfig | null;
  onClose: () => void;
  onSave: (request: SaveHostRequest) => void;
}

/** 根据编辑目标创建不含旧凭据的表单状态。 */
function formFromHost(host: HostConfig | null): SaveHostRequest {
  return {
    id: host?.id ?? '',
    name: host?.name ?? '',
    host: host?.host ?? '',
    port: host?.port ?? 22,
    username: host?.username ?? '',
    authType: host?.authType ?? AuthType.Password,
    password: '',
    privateKeyPath: host?.privateKeyPath ?? '',
    passphrase: '',
    remark: host?.remark ?? '',
  };
}

/** 渲染新建或编辑主机的安全凭据表单。 */
export default function HostEditorDialog({ open, editingHost, onClose, onSave }: Props) {
  const [form, setForm] = useState<SaveHostRequest>(() => formFromHost(editingHost));

  useEffect(() => {
    if (open) setForm(formFromHost(editingHost));
  }, [open, editingHost]);

  /** 更新单个表单字段。 */
  function update<K extends keyof SaveHostRequest>(key: K, value: SaveHostRequest[K]) {
    setForm((current) => ({ ...current, [key]: value }));
  }

  /** 提交表单并清除当前认证方式不使用的凭据字段。 */
  function submit() {
    onSave({
      ...form,
      id: form.id || crypto.randomUUID(),
      password: form.authType === AuthType.Password ? form.password : undefined,
      privateKeyPath: form.authType === AuthType.PrivateKey ? form.privateKeyPath : undefined,
      passphrase: form.authType === AuthType.PrivateKey ? form.passphrase : undefined,
    });
  }

  const textProps = { autoCapitalize: 'none', autoComplete: 'off', spellCheck: false };
  return <Modal open={open} title={editingHost ? '编辑连接' : '新建连接'} onCancel={onClose}
    onOk={submit} okText="保存连接" cancelText="取消" width={720} destroyOnHidden>
    <Form layout="vertical" className="host-form">
      <div className="form-grid">
        <Form.Item label="名称"><Input {...textProps} value={form.name} placeholder="生产服务器" onChange={(event) => update('name', event.target.value)} /></Form.Item>
        <Form.Item label="地址"><Input {...textProps} value={form.host} placeholder="192.168.1.12" onChange={(event) => update('host', event.target.value)} /></Form.Item>
        <Form.Item label="端口"><InputNumber min={1} max={65535} value={form.port} onChange={(value) => update('port', value ?? 22)} /></Form.Item>
        <Form.Item label="用户名"><Input {...textProps} value={form.username} placeholder="root" onChange={(event) => update('username', event.target.value)} /></Form.Item>
        <Form.Item label="认证方式"><Select value={form.authType} onChange={(value) => update('authType', value)}
          options={[{ label: '密码', value: AuthType.Password }, { label: '私钥', value: AuthType.PrivateKey }]} /></Form.Item>
        {form.authType === AuthType.Password ? <Form.Item label="密码"><Input.Password {...textProps} value={form.password}
          placeholder="留空则保持原密码不变" onChange={(event) => update('password', event.target.value)} /></Form.Item>
          : <Form.Item label="私钥路径"><Input {...textProps} value={form.privateKeyPath}
            placeholder="~/.ssh/id_rsa" onChange={(event) => update('privateKeyPath', event.target.value)} /></Form.Item>}
        {form.authType === AuthType.PrivateKey && <Form.Item label="私钥口令"><Input.Password {...textProps}
          value={form.passphrase} placeholder="留空则保持原口令不变" onChange={(event) => update('passphrase', event.target.value)} /></Form.Item>}
        <Form.Item label="备注" className="form-full"><Input.TextArea {...textProps} rows={3} value={form.remark}
          placeholder="业务说明 / 环境标签" onChange={(event) => update('remark', event.target.value)} /></Form.Item>
      </div>
    </Form>
  </Modal>;
}

// src/components/host/HostEditorDialog.vue
<script setup lang="ts">
import { computed, reactive, watch } from 'vue';
import {
  NModal, NCard, NForm, NFormItem, NInput, NInputNumber,
  NSelect, NButton, NSpace, NGrid, NGridItem,
} from 'naive-ui';
import { AuthType, type HostConfig, type SaveHostRequest } from '@/types/host';

const props = defineProps<{
  modelValue: boolean;
  editingHost: HostConfig | null;
}>();

const emit = defineEmits<{
  'update:modelValue': [boolean];
  /** 保存时提交 SaveHostRequest，含明文凭据，不含 ref 字段 */
  save: [SaveHostRequest];
}>();

/** 表单内部使用 SaveHostRequest 形状，含明文 password/passphrase */
const form = reactive<SaveHostRequest>({
  id: '',
  name: '',
  host: '',
  port: 22,
  username: '',
  auth_type: AuthType.Password,
  password: '',
  private_key_path: '',
  passphrase: '',
  remark: '',
});

const title = computed(() => (props.editingHost ? '编辑连接' : '新建连接'));

const authOptions = [
  { label: '密码', value: AuthType.Password },
  { label: '私钥', value: AuthType.PrivateKey },
];

/** 统一关闭主机表单文本输入的系统自动纠正，避免 WebView 自动首字母大写。 */
const textInputProps = {
  autocapitalize: 'none',
  autocomplete: 'off',
  spellcheck: false,
};

/**
 * 监听对话框打开与编辑目标变化，重置表单。
 * 编辑时从 HostConfig（含 ref 字段）初始化非敏感字段，密码字段留空让用户重新输入。
 */
watch(
  () => [props.modelValue, props.editingHost],
  () => {
    const source = props.editingHost;
    Object.assign(form, {
      id: source?.id ?? '',
      name: source?.name ?? '',
      host: source?.host ?? '',
      port: source?.port ?? 22,
      username: source?.username ?? '',
      auth_type: source?.auth_type ?? AuthType.Password,
      // 编辑时密码字段留空，用户需重新输入
      password: '',
      private_key_path: source?.private_key_path ?? '',
      // 编辑时口令字段留空，用户需重新输入
      passphrase: '',
      remark: source?.remark ?? '',
    });
  },
  { immediate: true },
);

/** 关闭对话框 */
function close() {
  emit('update:modelValue', false);
}

/** 提交表单，emit SaveHostRequest，后端负责安全存储明文凭据 */
function submit() {
  const request: SaveHostRequest = {
    ...form,
    id: form.id || crypto.randomUUID(),
    password: form.auth_type === AuthType.Password ? form.password : undefined,
    private_key_path:
      form.auth_type === AuthType.PrivateKey ? form.private_key_path : undefined,
    passphrase: form.auth_type === AuthType.PrivateKey ? form.passphrase : undefined,
  };
  emit('save', request);
}
</script>

<template>
  <NModal :show="modelValue" :mask-closable="true" @update:show="emit('update:modelValue', $event)">
    <NCard :title="title" style="width: min(720px, calc(100vw - 32px))" :bordered="false" role="dialog">
      <NForm label-placement="top" label-width="auto">
        <NGrid :cols="2" :x-gap="16">
          <NGridItem>
            <NFormItem label="名称">
              <NInput v-model:value="form.name" :input-props="textInputProps" placeholder="生产服务器" />
            </NFormItem>
          </NGridItem>
          <NGridItem>
            <NFormItem label="地址">
              <NInput v-model:value="form.host" :input-props="textInputProps" placeholder="192.168.1.12" />
            </NFormItem>
          </NGridItem>
          <NGridItem>
            <NFormItem label="端口">
              <NInputNumber v-model:value="form.port" :min="1" :max="65535" style="width: 100%" />
            </NFormItem>
          </NGridItem>
          <NGridItem>
            <NFormItem label="用户名">
              <NInput v-model:value="form.username" :input-props="textInputProps" placeholder="root" />
            </NFormItem>
          </NGridItem>
          <NGridItem>
            <NFormItem label="认证方式">
              <NSelect v-model:value="form.auth_type" :options="authOptions" />
            </NFormItem>
          </NGridItem>
          <NGridItem v-if="form.auth_type === AuthType.Password">
            <NFormItem label="密码">
              <NInput
                v-model:value="form.password"
                :input-props="textInputProps"
                type="password"
                show-password-on="click"
                placeholder="留空则保持原密码不变"
              />
            </NFormItem>
          </NGridItem>
          <NGridItem v-else>
            <NFormItem label="私钥路径">
              <NInput v-model:value="form.private_key_path" :input-props="textInputProps" placeholder="~/.ssh/id_rsa" />
            </NFormItem>
          </NGridItem>
          <NGridItem v-if="form.auth_type === AuthType.PrivateKey">
            <NFormItem label="私钥口令">
              <NInput
                v-model:value="form.passphrase"
                :input-props="textInputProps"
                type="password"
                show-password-on="click"
                placeholder="留空则保持原口令不变"
              />
            </NFormItem>
          </NGridItem>
          <NGridItem :span="2">
            <NFormItem label="备注">
              <NInput
                v-model:value="form.remark"
                :input-props="textInputProps"
                type="textarea"
                :rows="3"
                placeholder="业务说明 / 环境标签"
              />
            </NFormItem>
          </NGridItem>
        </NGrid>
      </NForm>
      <template #footer>
        <NSpace justify="end">
          <NButton @click="close">取消</NButton>
          <NButton type="primary" @click="submit">保存连接</NButton>
        </NSpace>
      </template>
    </NCard>
  </NModal>
</template>
