// src/components/home/HomeQuickActions.tsx
import { Button, Empty, Typography } from 'antd';
import type { MouseEvent } from 'react';
import type { HostConfig } from '@/types/host';

interface Props {
  hosts: HostConfig[];
  onOpen: (hostId: string) => void;
  onEdit: (hostId: string) => void;
  onRemove: (hostId: string) => void;
  onCreate: () => void;
}

/** 渲染首页主机快捷入口，并透传主机操作。 */
export default function HomeQuickActions({ hosts, onOpen, onEdit, onRemove, onCreate }: Props) {
  /** 阻止操作按钮触发主机连接。 */
  function runAction(event: MouseEvent, action: () => void) {
    event.stopPropagation();
    action();
  }

  return (
    <div className="home-quick-actions">
      <div className="home-host-scroll">
        {hosts.length === 0 ? (
          <Empty description="暂无保存的主机，点击下方按钮添加第一个 SSH 连接" />
        ) : (
          <div className="host-list">
            {hosts.map((host) => (
              <div key={host.id} className="host-btn" role="button" tabIndex={0}
                onClick={() => onOpen(host.id)} onKeyDown={(event) => event.key === 'Enter' && onOpen(host.id)}>
                <div className="host-main">
                  <div className="host-copy">
                    <Typography.Text strong>{host.name || host.host}</Typography.Text>
                    <Typography.Text type="secondary" className="host-address">
                      {host.username}@{host.host}:{host.port}
                    </Typography.Text>
                  </div>
                  <div className="host-actions">
                    <Button size="small" type="text" onClick={(event) => runAction(event, () => onEdit(host.id))}>编辑</Button>
                    <Button size="small" type="text" danger onClick={(event) => runAction(event, () => onRemove(host.id))}>删除</Button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
      <div className="create-section"><Button block onClick={onCreate}>+ 新建主机</Button></div>
    </div>
  );
}

// src/components/home/HomeQuickActions.vue
<script setup lang="ts">
import { NButton, NEmpty, NScrollbar, NText } from 'naive-ui';
import type { HostConfig } from '@/types/host';

defineProps<{
  hosts: HostConfig[];
}>();

const emit = defineEmits<{
  open: [hostId: string];
  edit: [hostId: string];
  remove: [hostId: string];
  create: [];
}>();
</script>

<template>
  <div class="home-quick-actions">
    <NScrollbar style="flex: 1; min-height: 0">
      <NEmpty
        v-if="hosts.length === 0"
        description="暂无保存的主机，点击下方按钮添加第一个 SSH 连接"
        style="margin-top: 60px"
      />
      <div v-else class="host-list">
        <div
          v-for="host in hosts"
          :key="host.id"
          class="host-btn"
          @click="emit('open', host.id)"
        >
          <div class="host-main">
            <div class="host-copy">
              <NText strong>{{ host.name || host.host }}</NText>
              <NText depth="3" style="font-size: 13px; font-family: monospace">
                {{ host.username }}@{{ host.host }}:{{ host.port }}
              </NText>
            </div>
            <div class="host-actions" @click.stop>
              <NButton
                size="tiny"
                quaternary
                class="host-action-btn host-action-btn--edit"
                @click="emit('edit', host.id)"
              >
                编辑
              </NButton>
              <NButton
                size="tiny"
                quaternary
                type="error"
                class="host-action-btn host-action-btn--remove"
                @click="emit('remove', host.id)"
              >
                删除
              </NButton>
            </div>
          </div>
        </div>
      </div>
    </NScrollbar>

    <div class="create-section">
      <NButton block @click="emit('create')">+ 新建主机</NButton>
    </div>
  </div>
</template>

<style scoped>
.home-quick-actions {
  display: flex;
  flex-direction: column;
  height: 100%;
  padding: 20px;
  gap: 16px;
}

.host-list {
  display: flex;
  flex-direction: column;
  gap: 10px;
  padding-right: 4px;
}

.host-btn {
  display: flex;
  flex-direction: column;
  gap: 10px;
  padding: 14px 18px;
  border: 1px solid var(--color-border);
  border-radius: 12px;
  background: var(--color-card-bg);
  cursor: pointer;
  transition: all 0.15s ease;
}

.host-btn:hover {
  border-color: var(--color-border-focus);
  background: var(--color-card-bg-hover);
  transform: translateY(-1px);
}

.host-main {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 12px;
}

.host-copy {
  display: flex;
  flex-direction: column;
  gap: 4px;
  min-width: 0;
}

.host-actions {
  display: flex;
  gap: 6px;
  flex-shrink: 0;
}

.host-action-btn {
  opacity: 0.8;
}

.host-btn:hover .host-action-btn {
  opacity: 1;
}

.create-section {
  flex-shrink: 0;
  padding-top: 12px;
  border-top: 1px solid var(--color-border);
}
</style>
